### ISSUE TITLE
Update header files to 3.2.3.791

### ISSUE THREAD

**Issue by kblomqvist** [jsnyder/avr32-toolchain#14]
How should we update header files, as those come now bundled with avr8 headers? See, http://www.atmel.com/Images/avr-headers-3.2.3.791.zip

Old version: 3.2.3.258 (currently installed with Makefile)
Newer version: 3.2.3.791

**Comment by kblomqvist** [comment]
This can be closed now.

**Comment by jsnyder** [comment]
Thanks for the help.
