### ISSUE TITLE
Update to latest toolchain version

### ISSUE THREAD

**Issue by johandc** [jsnyder/avr32-toolchain#19]
There is a new release available of the AVR toolchain. The version is now 3.4.1. But i cannot find the source files on atmels homepage. :-1: 
Does anybody here have insight in where atmel puts these releases?

**Comment by kblomqvist** [comment]
I guess you mean 3.4.2. It seems like binutils have been updated to 2.23.1 and GCC to 4.4.7. Newlib is still old 1.16.0 :(

Patches are here http://distribute.atmel.no/tools/opensource/Atmel-AVR-Toolchain-3.4.2/avr32/

But where are the header files?

**Comment by johandc** [comment]
No, i actually meant 3.4.1. The release of 3.4.2 happened less than 24 hours ago. It's so fresh that there is still no downloadable packages, nor headers for that matter.

I really wish that Atmel would start giving full access to their toolchains.

**Comment by kblomqvist** [comment]
Atmel's respond:

> Dear Cusstomer
> There are some issues while publishing the toolchain in the Site this time. The downloaded one is seems to be
> incomplete.  This is reported and complete toolchain is expected to be published in the site soon.

**Comment by johandc** [comment]
The sources for 3.4.2 as well as the headers are now available on atmel.com.
http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORLINUX.aspx

**Comment by johandc** [comment]
Just downloaded the pre-compiled 3.4.2 toolchain. And they have completely removed avr32-gdb :(
Seems like support for linux gets worse for every day that passes.

**Comment by kblomqvist** [comment]
How did you even used gdb before? avr32-gdbproxy hasn't been there a while.

**Comment by johandc** [comment]
Oh, it hasn't? How are we supposed to do debugging on AVR32 then?

**Comment by johandc** [comment]
Really bad news from Atmel:

Dear Customer,

Since atmel studio backend is present for debugging it is stopped working on GDB. 
In this version only linux 64 bit removes GDB.but it is intended to remove GDB from all versions.
So for debugging, you can use Atmel Studio or its toolchain(in windows), or use previous version for linux.

Sorry for the inconvenience caused. 

Best Regards, 
Matt Qian 
Atmel Technical Support Team

**Comment by kblomqvist** [comment]
Yep that's sad, but as far as I know, they have considered to add gdbproxy to their new atprogram command-line tool. We can just hope that it will be available for Linux as well. However, unit tests can beat in system debugging I think. I'm just setupping unit tests for Aery32 framework and researching what would be the best way to mock AVR32 registers (avr32/io.h).

**Comment by kblomqvist** [comment]
I have tried to build with these changes, https://github.com/aery32/avr32-toolchain/commit/5276d91597b2224bbf75ccc7d321c30b243a25b5

But got an error:

```
*** BFD does not support target avr32-unknown-none.
*** Look in bfd/config.bfd for supported targets.
```

Edit: AVR32 patches weren't applied correctly because of the changed directory structure. Building now.

**Comment by kblomqvist** [comment]
Try https://github.com/aery32/avr32-toolchain/tree/wip/gh-19

~~Although everything builds up, `avr32-gcc --version` shows wrong version for me.~~
