### ISSUE TITLE
build fails if PREFIX is changed without updating the PATH

### ISSUE THREAD

**Issue by ilg-ul** [jsnyder/avr32-toolchain#2]
I tried to change the PREFIX and the build failed, not finding  avr32-cc: and other newly built programs.

Adding the PREFIX/bin to the environment PATH before starting the build fixed the problem, so I assume somewhere there reference to PREFIX is missing.

Liviu

excerpt from the build:
...
touch stmp-targ-include
Making all in libc
Making all in argz
avr32-cc -B/Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/ -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/targ-include -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/newlib-1.16.0/newlib/libc/include -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"1.16.0\" -DPACKAGE_STRING=\"newlib\ 1.16.0\" -DPACKAGE_BUGREPORT=\"\" -I. -I../../../../../../newlib-1.16.0/newlib/libc/argz -Os -DPREFER_SIZE_OVER_SPEED -ffunction-sections -fdata-sections -D__NO_SYSCALLS__ -DHAVE_SYSTEM -DSMALL_MEMORY -DHAVE_GETTIMEOFDAY -fno-builtin      -ffunction-sections -fdata-sections -DPREFER_SIZE_OVER_SPEED -D__OPTIMIZE_SIZE__ -g -Os -fomit-frame-pointer -fno-unroll-loops -D__BUFSIZ__=128 -DSMALL_MEMORY -c -o lib_a-dummy.o `test -f 'dummy.c' || echo '../../../../../../newlib-1.16.0/newlib/libc/argz/'`dummy.c
avr32-cc -B/Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/ -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/targ-include -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/newlib-1.16.0/newlib/libc/include -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"1.16.0\" -DPACKAGE_STRING=\"newlib\ 1.16.0\" -DPACKAGE_BUGREPORT=\"\" -I. -I../../../../../../newlib-1.16.0/newlib/libc/argz -Os -DPREFER_SIZE_OVER_SPEED -ffunction-sections -fdata-sections -D__NO_SYSCALLS__ -DHAVE_SYSTEM -DSMALL_MEMORY -DHAVE_GETTIMEOFDAY -fno-builtin      -ffunction-sections -fdata-sections -DPREFER_SIZE_OVER_SPEED -D__OPTIMIZE_SIZE__ -g -Os -fomit-frame-pointer -fno-unroll-loops -D__BUFSIZ__=128 -DSMALL_MEMORY -c -o lib_a-argz_add.o `test -f 'argz_add.c' || echo '../../../../../../newlib-1.16.0/newlib/libc/argz/'`argz_add.c
avr32-cc -B/Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/ -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/targ-include -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/newlib-1.16.0/newlib/libc/include -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"1.16.0\" -DPACKAGE_STRING=\"newlib\ 1.16.0\" -DPACKAGE_BUGREPORT=\"\" -I. -I../../../../../../newlib-1.16.0/newlib/libc/argz -Os -DPREFER_SIZE_OVER_SPEED -ffunction-sections -fdata-sections -D__NO_SYSCALLS__ -DHAVE_SYSTEM -DSMALL_MEMORY -DHAVE_GETTIMEOFDAY -fno-builtin      -ffunction-sections -fdata-sections -DPREFER_SIZE_OVER_SPEED -D__OPTIMIZE_SIZE__ -g -Os -fomit-frame-pointer -fno-unroll-loops -D__BUFSIZ__=128 -DSMALL_MEMORY -c -o lib_a-argz_add_sep.o `test -f 'argz_add_sep.c' || echo '../../../../../../newlib-1.16.0/newlib/libc/argz/'`argz_add_sep.c
avr32-cc -B/Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/ -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/targ-include -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/newlib-1.16.0/newlib/libc/include -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"1.16.0\" -DPACKAGE_STRING=\"newlib\ 1.16.0\" -DPACKAGE_BUGREPORT=\"\" -I. -I../../../../../../newlib-1.16.0/newlib/libc/argz -Os -DPREFER_SIZE_OVER_SPEED -ffunction-sections -fdata-sections -D__NO_SYSCALLS__ -DHAVE_SYSTEM -DSMALL_MEMORY -DHAVE_GETTIMEOFDAY -fno-builtin      -ffunction-sections -fdata-sections -DPREFER_SIZE_OVER_SPEED -D__OPTIMIZE_SIZE__ -g -Os -fomit-frame-pointer -fno-unroll-loops -D__BUFSIZ__=128 -DSMALL_MEMORY -c -o lib_a-argz_append.o `test -f 'argz_append.c' || echo '../../../../../../newlib-1.16.0/newlib/libc/argz/'`argz_append.c
avr32-cc -B/Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/ -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/build/newlib/avr32/newlib/targ-include -isystem /Users/ilg/work/AVR32/jsnyder-avr32-toolchain-af9fff3/newlib-1.16.0/newlib/libc/include -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"1.16.0\" -DPACKAGE_STRING=\"newlib\ 1.16.0\" -DPACKAGE_BUGREPORT=\"\" -I. -I../../../../../../newlib-1.16.0/newlib/libc/argz -Os -DPREFER_SIZE_OVER_SPEED -ffunction-sections -fdata-sections -D__NO_SYSCALLS__ -DHAVE_SYSTEM -DSMALL_MEMORY -DHAVE_GETTIMEOFDAY -fno-builtin      -ffunction-sections -fdata-sections -DPREFER_SIZE_OVER_SPEED -D__OPTIMIZE_SIZE__ -g -Os -fomit-frame-pointer -fno-unroll-loops -D__BUFSIZ__=128 -DSMALL_MEMORY -c -o lib_a-argz_count.o `test -f 'argz_count.c' || echo '../../../../../../newlib-1.16.0/newlib/libc/argz/'`argz_count.c
/bin/sh: avr32-cc: command not found
make[6]: **\* [lib_a-dummy.o] Error 127
make[6]: **\* Waiting for unfinished jobs....
/bin/sh: avr32-cc: command not found
make[6]: **\* [lib_a-argz_add.o] Error 127
/bin/sh: avr32-cc: command not found
/bin/sh: avr32-cc: command not found
make[6]: **\* [lib_a-argz_add_sep.o] Error 127
make[6]: **\* [lib_a-argz_append.o] Error 127
/bin/sh: avr32-cc: command not found
make[6]: **\* [lib_a-argz_count.o] Error 127

**Comment by jsnyder** [comment]
Hmm.. is this related to the sudo issue you mentioned before?  PREFIX/bin is added in the Makefile and should work correctly if you use PREFIX or SUPP_PREFIX to modify paths up top.

That PATH variable is supposed to pass through to running subtasks automatically.

**Comment by ilg-ul** [comment]
I opened a fresh terminal, manually patched the script that prepares my environment and calls your Makefile to no longer update the PATH and... it completed properly :-)

sorry for the inconvenience, I assume it was a transient problem, most probably due to inconsistent environment.

Liviu
