### ISSUE TITLE
AVR32PATCHES_URL is broken

### ISSUE THREAD

**Issue by kblomqvist** [jsnyder/avr32-toolchain#9]
Atmel AVR Studio 5 beta has been removed from http://distribute.atmel.no/tools/opensource/ and thus patches url is broken. There is also a newer release available:

AVR_PATCH_REV=3.2.3.261
AVR32PATCHES_URL=http://www.atmel.com/dyn/resources/prod_documents/$(AVR32PATCHES_ARCHIVE)

The old value of AVR32PATCHES_MD5 worked for me but it is likely changed although I did not get any errors.

**Comment by martinwguy** [comment]
Under http://distribute.atmel.no/tools/opensource/avr32-gcc instead there are now separate directories containing the patches broken out into separate files under directories called gcc-4.4.3 and so on.
I don't know which is better - maybe atmel will update their broken-out patch directories as they fix more bugs and add optimizations?

**Comment by kblomqvist** [comment]
I would prefer broken-out patches if it's only feasible to use those. Furthermore someone has fixed checksum checking in  https://github.com/IcyLabs/avr32-toolchain/commit/aa7a59d394a0855d7bcb4721a32488e9ec965da3. Could this be the reason why I managed to use the different AVR32PATCHES_ARCHIVE with the old checksum?

**Comment by martinwguy** [comment]
On 28 December 2011 20:40, Kim Blomqvist
reply@reply.github.com
wrote:

> someone has fixed checksum checking in  https://github.com/IcyLabs/avr32-toolchain/commit/aa7a59d394a0855d7bcb4721a32488e9ec965da3. Could this be the reason why I managed to use the different AVR32PATCHES_ARCHIVE with the old checksum?

yes
